### ISSUE TITLE
克隆演示

### ISSUE THREAD

**Issue by smallsnake5** [webjyh/MPreview.mobile#5]
为什么我克隆下来以后，点击浏览，没有图片出现
https://www.loom.com/share/432c2d7fdd5140adaebad7181bc52ffa

**Comment by webjyh** [comment]
项目很早了，应该是以前的 CDN图片域名挂了，在index.html 里面的代码
```javascript
// 原来的
var imgHost = 'http://7jpp73.com1.z0.glb.clouddn.com/'

// 这里你可以换成
var imgHost = 'http://gitphoto.webjyh.com/'
```
我推荐使用这个相册库 [PhotoSwipe](https://github.com/dimsemenov/PhotoSwipe)

**Comment by smallsnake5** [comment]
嗯嗯，谢谢你的回复。你的这个组件我自己放了图片进去以后，我发现没有办法点击固定图片展示，每次都从第一张开始展示然后滑动，不符合我目前的需求，已经用了其他的来写了，谢谢你

**Comment by webjyh** [comment]
@smallsnake5 不客气
